Revert "handling of luaposix for dynamic environments"
This reverts commit 37faad2994885b276222ff72d868368499714009.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"


Origin commit data
------------------
Commit: https://github.com/neutrino-images/ni-neutrino/commit/8c88dfdc204577cbbc4ecb7af07882c0ff373245
Author: Stefan Seyfried <seife@tuxbox-git.slipkontur.de>
Date: 2013-04-27 (Sat, 27 Apr 2013)



------------------
This commit was generated by Migit