Revert "handling of luaposix for dynamic environments"
This reverts commit 68ca32f3aaeeebbcd24023df7eba2a3351e77728.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"


Origin commit data
------------------
Branch: ni/coolstream
Commit: https://github.com/neutrino-images/ni-neutrino/commit/8c88dfdc204577cbbc4ecb7af07882c0ff373245
Author: Stefan Seyfried <seife@tuxbox-git.slipkontur.de>
Date: 2013-04-27 (Sat, 27 Apr 2013)



------------------
This commit was generated by Migit