Revert "handling of luaposix for dynamic environments"
This reverts commit 1b22d0bd4f09096d0470de760f9dcd43bab2a47d.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"


Origin commit data
------------------
Branch: master
Commit: https://github.com/neutrino-images/ni-neutrino/commit/8c88dfdc204577cbbc4ecb7af07882c0ff373245
Author: Stefan Seyfried <seife@tuxbox-git.slipkontur.de>
Date: 2013-04-27 (Sat, 27 Apr 2013)



------------------
This commit was generated by Migit